### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by VanTuz5** [ppldl/p_pl_dl#3]
![image](https://user-images.githubusercontent.com/39066280/145734887-7445e99d-7f4c-4da3-9260-dbe5d3529005.png)

**Comment by otongS** [comment]
you need to download the requirement first I think.

pip install yt_dlp
and the rest in requirements.txt

**Comment by ppldl** [comment]
> you need to download the requirement first I think.
> 
> pip install yt_dlp and the rest in requirements.txt

Yup.
