### ISSUE TITLE
Spankbang outputs Errno 2

### ISSUE THREAD

**Issue by lowkeyalextho** [ppldl/p_pl_dl#9]
Installed via git clone directory.
Cookies ripped with get cookies.txt extension: https://chrome.google.com/webstore/detail/get-cookiestxt/bgaddhkoddajcdgocldbbfleckgcbcid?hl=en
Enclosed are my cookies (with identifying details redacted), and the output from running the program.
Can and will provide more if needed.
[spankbang_redacted_cookies.txt](https://github.com/ppldl/p_pl_dl/files/10418730/spankbang_redacted_cookies.txt)

> C:\Users\yaboi\Downloads\p_pl_dl>py p_pl_dl_main.py -i "C:\Users\yaboi\Downloads\p_pl_dl\urls.txt" -c "C:\Users\yaboi\Downloads\p_pl_dl\spankbang.com_cookies.txt" -d "C:\Users\yaboi\Dropbox\videos\Porn\titjobs"
> 
> Working download directory: C:\Users\yaboi\Dropbox\videos\Porn\titjobs
> 
> Cookies source: C:\Users\yaboi\Downloads\p_pl_dl\spankbang.com_cookies.txt
> 
> Using the following input source: C:\Users\yaboi\Downloads\p_pl_dl\urls.txt
> 
> Video limit per URL = None
> URL: https://spankbang.com/1p8hh/playlist/minna+no+paizuri
> 
> Detected websites:
> {
>     "lewdthots": false,
>     "pornhub": false,
>     "porntrex": false,
>     "pornve": false,
>     "spankbang": true,
>     "xhamster": false,
>     "xvideos": false,
>     "youporn": false
> }
> 
> Running spankbang extractor for https://spankbang.com/1p8hh/playlist/minna+no+paizuri
> 
> Initial connection status: 200
> 
> Playlist detected. Getting videos...
> Found 100 videos on page 01...
> Found 100 videos on page 02...
> Found 11 videos on page 03...
> No videos found on page 4. Stopping...
> Time elapsed: 1.2 minutes
> Found 211 video URLs in the playlist
> 
> 
> 
> Traceback (most recent call last):
>   File "C:\Users\yaboi\Downloads\p_pl_dl\p_pl_dl_main.py", line 94, in main
>     dExtractors[sSite].run(sUrl, sCookieSource=None, nVideoLimit=nVideoLimit)       # Cookies should already be parsed and available when going through main
>   File "C:\Users\yaboi\Downloads\p_pl_dl\p_pl_dl_sb.py", line 56, in run
>     with open(sArchive) as file:
> FileNotFoundError: [Errno 2] No such file or directory: '.\\\\sites\\\\spankbang\\\\dl_hist_spankbang.txt'

**Comment by lowkeyalextho** [comment]
> YOU ARE PROBABLY USING WIN 7. I GOT THE SAME ERROR. Install win 10, and thats solved. Enjoy.

I am using windows 11. If not using windows 10 is the issue, then I guess I'm outta luck.

**Comment by humaintenance** [comment]
@lowkeyalextho the script treats the destination argument (-d in your command) as the current working directory, and doesn't appear to create the directory path it needs when running the script. As a bodged _"fix"_ for this, do the following:

In your directory `C:\Users\yaboi\Dropbox\videos\Porn\titjobs`, create a folder called `sites`, then in that create a folder called `spankbang`, and then in that create a txt file called `dl_hist_spankbang.txt`.

so you should then have the following directory and file: `C:\Users\yaboi\Dropbox\videos\Porn\titjobs\sites\spangbang\dl_hist_spankbang.txt`

The videos will download into this spankbang folder, so you'll probably have to move them `C:\Users\yaboi\Dropbox\videos\Porn\titjobs` after they've finished downloading, but its better than nothing.

That should hopefully work for you, it did for me.

**Comment by lowkeyalextho** [comment]
thank you, that worked for me!
